/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Admin;

import com.mysql.jdbc.Connection;
import java.awt.Image;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.io.File;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.time.Instant;
import java.util.Date;
import java.util.Vector;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author warun
 */
public class Lecture_Attendens extends javax.swing.JInternalFrame {
    
    java.sql.Connection con;
    
    /**
     * Creates new form Profiles
     */
    public Lecture_Attendens() {
        initComponents();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI ui=(BasicInternalFrameUI)this.getUI();
        ui.setNorthPane(null);
        
        con=DBConnect.connect();
        PreparedStatement pst;
        ResultSet rs;
        
        this.setSize(1200,800);
        
        displayTable();
        setDepartment();
        
        imgPath.setVisible(false);
    }
    
    public void tableClick(){
       
    }
    
    public void displayTable(){
        Admin admin=new Admin();
        
       DefaultTableModel model=(DefaultTableModel) users.getModel();
        
         model.setRowCount(0);
         admin.display();
         
         for (Object data : admin.getData()) {
            model.addRow((Vector)data);
        }
    }
    
    
    public void setDepartment(){   
        
        try {
            String sql="select * from department";
            PreparedStatement pst=con.prepareStatement(sql);
            ResultSet rs=pst.executeQuery();
            
            while(rs.next()) { 
           department.addItem(rs.getString("name"));
           
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
       
        
    }
    
     public void displayStudent(){
         Users std=new Users();
        
         DefaultTableModel model=(DefaultTableModel) users.getModel();
        
         model.setRowCount(0);
         std.display();
         
         for (Object data : std.getData()) {
            model.addRow((Vector)data);
        }
    }
     
     
   
     
     
    
    
    public void clear(){
            f_name.setText("");
            l_name.setText("");
            Date date=new Date(01/01/1999);
            dob.setDate(date);
            gender.setSelectedItem("");
            nic.setText("");
            address.setText("");
            contact.setText("");
            email.setText("");
            imageLbl.setIcon(null);
            imgPath.setText("");
            Id.setText("");
            password.setText("");
            
            f_name.setText("");
            l_name.setText("");
            dob.setDate(date);
            gender.setSelectedItem("");
            nic.setText("");
            address.setText("");
            contact.setText("");
            email.setText("");
            imageLbl.setIcon(null);
            imgPath.setText("");
            
            jButton6.setEnabled(true);
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        users = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setPreferredSize(new java.awt.Dimension(1155, 600));

        users.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student Id", "Course Id", "Date", "Hourse", "Department", "Levels", "Status"
            }
        ));
        users.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usersMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(users);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 901, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(273, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
                .addGap(683, 683, 683))
        );

        jTabbedPane1.addTab("Attendance", jPanel3);

        getContentPane().add(jTabbedPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void usersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersMouseClicked
        try {
            Users std=new Users();
            DefaultTableModel d = (DefaultTableModel)users.getModel();
            int row=users.getSelectedRow();
            int id=(int) users.getValueAt(row, 0);
            //JOptionPane.showMessageDialog(null, row);
            int count=users.getRowCount();

            //JOptionPane.showMessageDialog(null, id);
            std.select(id);
            f_name.setText(std.getF_name());
            l_name.setText(std.getL_name());
            Date date=new SimpleDateFormat("yyyy-MM-dd").parse(std.getDob());
            dob.setDate(date);
            gender.setSelectedItem(std.getGender());
            nic.setText(std.getNic());
            address.setText(std.getAddress());
            contact.setText(std.getContact().toString());
            email.setText(std.getEmail());
            department.setSelectedItem(std.getDepartment());
            Id.setText(std.getUser_id().toString());
            password.setText(std.getPassword());

            String filname=std.getImage();
            imgPath.setText(filname);
            Image getAbsolutePath=null;
            ImageIcon icon=new ImageIcon(filname);
            Image image=icon.getImage().getScaledInstance(imageLbl.getWidth(),imageLbl.getHeight(), Image.SCALE_SMOOTH);
            imageLbl.setIcon(new ImageIcon(image));

            jButton6.setEnabled(false);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_usersMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTable users;
    // End of variables declaration//GEN-END:variables

        
    
    
}


